####Program layout antarmuka jendela form identitas . py####
# Form implementation generated from reading ui file ’ identitas . ui ’
#
# Created by: PyQt5 UI code generator 5.9.2
#

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Input(object) :
    def setupUi(self,Input) :
        Input.setObjectName("Input")
        Input.resize(374, 715)
        self.groupBox_klienlama = QtWidgets.QGroupBox(Input)
        self.groupBox_klienlama.setEnabled(True)
        self.groupBox_klienlama.setGeometry(QtCore.QRect(30, 20, 311, 221))
        self.groupBox_klienlama.setFlat(False)
        self.groupBox_klienlama.setCheckable(True)
        self.groupBox_klienlama.setChecked(False)
        self.groupBox_klienlama.setObjectName("groupBox_klienlama")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_klienlama)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 211, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins (0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label )
        self.label_tb_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_tb_2.setObjectName("label_tb_2")
        self.verticalLayout_3.addWidget(self.label_tb_2)
        self.label_bb_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_bb_2.setObjectName("label_bb_2")
        self.verticalLayout_3.addWidget(self.label_bb_2)
        self.label_op_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_op_2.setObjectName("label_op_2")
        self.verticalLayout_3.addWidget(self.label_op_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem )
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_id.setObjectName("input_id")
        self.verticalLayout_4.addWidget(self.input_id )
        self.input_tb_lama = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_tb_lama.setObjectName("input_tb_lama")
        self.verticalLayout_4.addWidget(self.input_tb_lama)
        self.input_bb_lama = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_bb_lama.setObjectName("input_bb_lama")
        self.verticalLayout_4.addWidget(self.input_bb_lama)
        self.input_op_lama = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_op_lama.setObjectName("input_op_lama")
        self.verticalLayout_4.addWidget(self.input_op_lama)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tombol_ok_lama = QtWidgets.QPushButton(self.layoutWidget)
        self.tombol_ok_lama.setObjectName("tombol_ok_lama")
        self.verticalLayout_5.addWidget(self.tombol_ok_lama)
        self.groupBox_klienbaru = QtWidgets.QGroupBox(Input)
        self.groupBox_klienbaru.setEnabled(True)
        self.groupBox_klienbaru.setGeometry(QtCore.QRect(30, 270, 311, 441))
        self.groupBox_klienbaru.setFlat( False )
        self.groupBox_klienbaru.setCheckable(True)
        self.groupBox_klienbaru.setChecked(True)
        self.groupBox_klienbaru.setObjectName("groupBox_klienbaru")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_klienbaru)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 40, 211, 380))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins (0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1 , 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(" verticalLayout_2 ")
        self.label_nama = QtWidgets.QLabel(self .layoutWidget_2)
        self.label_nama.setObjectName("label_nama")
        self.verticalLayout_2.addWidget(self .label_nama)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2 )
        self.label_ttl = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_ttl.setObjectName("label_ttl")
        self.verticalLayout_2.addWidget(self.label_ttl )
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_jk = QtWidgets.QLabel(self .layoutWidget_2)
        self.label_jk.setObjectName("label_jk")
        self.verticalLayout_2.addWidget(self.label_jk )
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_tb = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_tb.setObjectName("label_tb")
        self.verticalLayout_2.addWidget(self.label_tb )
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_bb = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_bb.setObjectName("label_bb")
        self.verticalLayout_2.addWidget(self.label_bb )
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.label_op = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_op.setObjectName("label_op")
        self.verticalLayout_2.addWidget(self.label_op )
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 258, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_nama = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_nama.setObjectName("input_nama")
        self.verticalLayout.addWidget(self.input_nama)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)
        self.input_jk = QtWidgets.QComboBox(self.layoutWidget_2)
        self.input_jk.setObjectName("input_jk")
        self.input_jk.addItem("")
        self.input_jk.addItem("")
        self.verticalLayout.addWidget(self.input_jk)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem9)
        self.input_tl = QtWidgets.QDateEdit(self.layoutWidget_2)
        self.input_tl.setObjectName("input_tl")
        self.verticalLayout.addWidget(self.input_tl)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem10)
        self.input_tb = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_tb.setObjectName("input_tb")
        self.verticalLayout.addWidget(self.input_tb)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self . verticalLayout.addItem(spacerItem11)
        self.input_bb = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_bb.setObjectName("input_bb")
        self.verticalLayout.addWidget(self.input_bb)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem12)
        self.input_op = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_op.setObjectName("input_op")
        self.verticalLayout.addWidget(self.input_op)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout , 0, 0, 1, 1)
        self.tombol_ok_baru = QtWidgets.QPushButton(self.layoutWidget_2)
        self.tombol_ok_baru.setObjectName("tombol_ok_baru")
        self.gridLayout.addWidget(self.tombol_ok_baru, 2, 0, 1, 1)
        self.retranslateUi(Input)
        QtCore.QMetaObject.connectSlotsByName(Input)

    def retranslateUi (self, Input) :
        _translate = QtCore.QCoreApplication.translate
        Input .setWindowTitle( _translate("Input", "Form"))
        self.groupBox_klienlama.setTitle(_translate("Input", "Klien Lama"))
        self.label.setText( _translate ("Input", "Nomor ID"))
        self.label_tb_2.setText( _translate("Input", "Tinggi Badan"))
        self.label_bb_2.setText (_translate("Input", "Berat Badan"))
        self.label_op_2.setText( _translate ("Input", "Operator") )
        self.tombol_ok_lama.setText(_translate("Input", "OK"))
        self.groupBox_klienbaru.setTitle(_translate("Input", "Klien Baru"))
        self.label_nama.setText(_translate("Input", "Nama"))
        self.label_ttl.setText(_translate("Input", " Jenis Kelamin"))
        self.label_jk.setText(_translate("Input", "Tanggal Lahir") )
        self.label_tb.setText(_translate("Input", "Tinggi Badan"))
        self.label_bb.setText(_translate("Input", "Berat Badan"))
        self.label_op.setText(_translate("Input", "Operator") )
        self.input_jk.setItemText(0,_translate("Input", "Laki-Laki"))
        self.input_jk.setItemText(1,_translate("Input", "Perempuan"))
        self.input_tl.setDisplayFormat(_translate("Input", "dd/MM/yyyy"))
        self.tombol_ok_baru.setText(_translate("Input", "OK"))

########################################
