####Program layout antarmuka jendela pengukuran ppgbp.py####




# Created by: PyQt5 UI code generator 5.9.2
#

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 620)
        MainWindow.setStyleSheet("background-color: rgb(8, 8, 8);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tombol_selesai = QtWidgets.QPushButton(self.centralwidget )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tombol_selesai.sizePolicy().hasHeightForWidth())
        self.tombol_selesai.setSizePolicy(sizePolicy)
        self.tombol_selesai.setStyleSheet("color : rgb (35, 35, 35);")
        self.tombol_selesai.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tombol_selesai.setObjectName("tombol_selesai")
        self.gridLayout_5.addWidget(self.tombol_selesai, 0, 4, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.grafik_sistole = PlotWidget(self.centralwidget)
        self.grafik_sistole.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafik_sistole.sizePolicy().hasHeightForWidth())
        self.grafik_sistole.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.grafik_sistole.setFont(font)
        self.grafik_sistole.setObjectName("grafik_sistole")
        self.gridLayout.addWidget(self.grafik_sistole, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout , 1, 0, 3, 3)
        self.waktu = QtWidgets.QLabel(self.centralwidget )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch (0)
        sizePolicy.setHeightForWidth(self.waktu.sizePolicy().hasHeightForWidth())
        self.waktu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.waktu.setFont(font)
        self.waktu.setStyleSheet("color : rgb(238, 238, 238);")
        self.waktu.setText("")
        self.waktu.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.waktu.setObjectName("waktu")
        self.gridLayout_5.addWidget(self.waktu, 4, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem , 2, 3, 1, 2)
        self.tombol_mulai = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tombol_mulai.sizePolicy().hasHeightForWidth())
        self.tombol_mulai.setSizePolicy(sizePolicy)
        self.tombol_mulai.setStyleSheet("color : rgb(35, 35, 35);")
        self.tombol_mulai.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tombol_mulai.setObjectName("tombol_mulai")
        self.gridLayout_5.addWidget(self.tombol_mulai, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred , QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet ("color: rgb(238, 238, 238);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred ,QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 1, 1, 1)
        #self.nama_operator = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred ,QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.nama_operator.sizePolicy().hasHeightForWidth())
        #self.nama_operator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        #self.nama_operator.setFont(font)
        #self.nama_operator.setStyleSheet("color : rgb(238, 238, 238);")
        #self.nama_operator.setText("")
        #self.nama_operator.setObjectName("nama_operator")
        #self.gridLayout_4.addWidget(self.nama_operator, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.judul = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.judul.sizePolicy().hasHeightForWidth())
        self.judul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.judul.setStyleSheet("color: rgb(238, 238, 238);")
        self.judul.setAlignment(QtCore.Qt.AlignCenter)
        self.judul.setObjectName("judul")
        self.gridLayout_5.addWidget(self.judul, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        #self.tanggal = QtWidgets.QLabel(self.centralwidget )
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        #self.tanggal.setFont(font)
        #self.tanggal.setStyleSheet("color: rgb(238, 238, 238);")
        #self.tanggal.setText("")
        #self.tanggal.setObjectName("tanggal")
        #self.gridLayout_3.addWidget(self.tanggal, 0, 3, 1, 2)
        #self.kelamin = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        #self.kelamin.setFont(font)
        #self.kelamin.setStyleSheet("color: rgb(238, 238, 238);")
        #self.kelamin.setText("")
        #self.kelamin.setObjectName("kelamin")
        #self.gridLayout_3.addWidget(self.kelamin, 3, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(238, 238, 238);")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        #self.usia = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        #self.usia.setFont(font)
        #self.usia.setStyleSheet("color : rgb(238, 238, 238);")
        #self.usia.setText("")
        #self.usia.setObjectName("usia")
        #self.gridLayout_3.addWidget(self.usia, 4, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 4, 1, 1)
        #self.nama_klien = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        #self.nama_klien.setFont(font)
        #self.nama_klien.setStyleSheet("color: rgb(238, 238, 238);")
        #self.nama_klien.setText("")
        #self.nama_klien.setObjectName("nama_klien")
        #self.gridLayout_3.addWidget(self.nama_klien, 2, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        #self.berat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        #self.berat.setFont(font)
        #self.berat.setStyleSheet("color: rgb(238, 238, 238);")
        #self.berat.setText("")
        #self.berat.setObjectName("berat")
        #self.gridLayout_3.addWidget(self.berat, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 4, 1, 1)
        #self.nomor_id = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        #self.nomor_id.setFont(font)
        #self.nomor_id.setStyleSheet("color: rgb(238, 238, 238);")
        #self.nomor_id.setText("")
        #self.nomor_id.setObjectName("nomor_id")
        #self.gridLayout_3.addWidget(self.nomor_id, 1, 3, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color : rgb(238, 238, 238);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet ("color: rgb(238, 238, 238);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 2, 1, 1)
        #self.tinggi = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        #self.tinggi.setFont(font)
        #self.tinggi.setStyleSheet("color: rgb(238, 238, 238);")
        #self.tinggi.setText("")
        #self.tinggi.setObjectName("tinggi")
        #self.gridLayout_3.addWidget(self.tinggi, 5, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(238, 238, 238);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 6, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 3, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_diastole = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_diastole.sizePolicy().hasHeightForWidth())
        self.label_diastole.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_diastole.setFont(font)
        self.label_diastole.setStyleSheet("color: rgb(0, 153, 255);")
        self.label_diastole.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diastole.setObjectName("label_diastole")
        self.gridLayout_2.addWidget(self.label_diastole, 3, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 153, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 0, 76);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 0, 76);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_sistole = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sistole.sizePolicy().hasHeightForWidth())
        self.label_sistole.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_sistole.setFont(font)
        self.label_sistole.setStyleSheet("color: rgb(255, 0, 76);")
        self.label_sistole.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sistole.setObjectName("label_sistole")
        self.gridLayout_2.addWidget(self.label_sistole, 1, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 153, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 3, 3, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tombol_selesai.setText(_translate("MainWindow", "Selesai"))
        self.tombol_mulai.setText(_translate("MainWindow", "Mulai"))
        #self.label_9.setText(_translate("MainWindow", "Operator"))
        #self.label_28.setText(_translate("MainWindow", ":"))
        self.judul.setText(_translate("MainWindow", "Pengukuran Tekanan Darah"))
        #self.label_2.setText(_translate("MainWindow", "Usia"))
        #self.label_3.setText(_translate("MainWindow", "Jenis Kelamin"))
        #self.label_26.setText(_translate("MainWindow", ":"))
        #self.label_18.setText(_translate("MainWindow", "cm"))
        #self.label_20.setText(_translate("MainWindow", "Tanggal"))
        #self.label.setText(_translate("MainWindow", "Nama"))
        #self.label_12.setText(_translate("MainWindow", "ID"))
        #self.label_24.setText(_translate("MainWindow", ":"))
        #self.label_5.setText(_translate("MainWindow", "Berat Badan"))
        #self.label_22.setText(_translate("MainWindow", ":"))
        #self.label_19.setText(_translate("MainWindow", "kg"))
        #self.label_4.setText(_translate("MainWindow", "Tinggi Badan"))
        #self.label_17.setText(_translate("MainWindow", "tahun"))
        #self.label_21.setText(_translate("MainWindow", ":"))
        #self.label_25.setText(_translate("MainWindow", ":"))
        #self.label_23.setText(_translate("MainWindow", ":"))
        #self.label_27.setText(_translate("MainWindow", ":"))
        self.label_diastole.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "mmHg"))
        self.label_8.setText(_translate("MainWindow", "Sistole") )
        self.label_7.setText(_translate("MainWindow", "mmHg"))
        self.label_sistole.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Diastole"))


